server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clientdb
    username: postgres
    password: admin

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
<<<<<<< HEAD
        dialect: org.hibernate.dialect.PostgreSQLDialect
=======
    database-platform: org.hibernate.dialect.PostgreSQLDialect
>>>>>>> ac5d0b1dbbeffb64064f6a6f32a2f6215a4123ce
