server:
  port: 8081

spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5432/clientdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #ddl-auto: update
    #show-sql: true
    #properties:
    #  hibernate:
    #    format_sql: true
     #   dialect: org.hibernate.dialect.PostgreSQLDialect
