server:
  port: 8095

spring:
  application:
    name: delivery-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/deliverydb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/