server:
  port: 8085

spring:
  application:
    name: delivery-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/deliverydb

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka