server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8084
          predicates:
            - Path=/users/**
        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Users Service
        url: /users/v3/api-docs
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Product Service
        url: /products/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #DNS
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1