server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #DNS
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1